name: flutter_mh_dufte_depot_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  syncfusion_flutter_charts: ^26.1.35
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env # Wichtig: Diese Zeile muss exakt zwei Leerzeichen eingerückt sein
