// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqZtDp7XERwh7nB35BTAlRPY7lswmE_80',
    appId: '1:654629038116:web:121ba1cd5530d62627d0b1',
    messagingSenderId: '654629038116',
    projectId: 'duftesdepot',
    authDomain: 'duftesdepot.firebaseapp.com',
    storageBucket: 'duftesdepot.firebasestorage.app',
    measurementId: 'G-1Q3Y9SWY2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBymkmTaEPK3ww3SAalciayKVgEtFoZ4VM',
    appId: '1:654629038116:android:63e1adf2dd07660a27d0b1',
    messagingSenderId: '654629038116',
    projectId: 'duftesdepot',
    storageBucket: 'duftesdepot.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqZtDp7XERwh7nB35BTAlRPY7lswmE_80',
    appId: '1:654629038116:web:e87e87bf21e255c627d0b1',
    messagingSenderId: '654629038116',
    projectId: 'duftesdepot',
    authDomain: 'duftesdepot.firebaseapp.com',
    storageBucket: 'duftesdepot.firebasestorage.app',
    measurementId: 'G-Q9868MGW72',
  );
}
